name: Docker build

on: workflow_dispatch
    
jobs:
  docker:
    permissions:
      id-token: write
      contents: read
    name: apply
    runs-on: ubuntu-latest
    timeout-minutes: 60
    environment: test
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        name: Configure AWS Credentials
        with:
          aws-region: "eu-west-2"
          role-to-assume: "arn:aws:iam::111789616134:role/github-oidc-provider-aws"
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: "111789616134"

      - name: Build, tag, and push image to Amazon ECR
        id: build-publish
        shell: bash
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: "evm-rpc-test"
          IMAGE_TAG: "latest"
        run: |
          docker build "." -f "Dockerfile-actions" -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          docker push "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "IMAGE $IMAGE_TAG is pushed to $ECR_REGISTRY/$ECR_REPOSITORY"
          echo "image_tag=$IMAGE_TAG" 
          echo "full_image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
